name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: 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
          environment-url: 'https://api.github.com/user/repos'
          environment: production
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
