name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: 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
          environment-url: 'https://atl-test-rpatil.atlassian.net'
          environment: production
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
